export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole =
  | "admin"
  | "partner"
  | "manager"
  | "senior_associate"
  | "article_trainee"
  | "staff"
  | "client";

export type EmploymentStatus =
  | "confirmed"
  | "probation"
  | "notice_period"
  | "intern"
  | "resigned"
  | "deactivated";

export type InvoiceType = "proforma" | "tax_invoice";

export type DSCLocation =
  | "ca_office"
  | "cs_office"
  | "client_office"
  | "in_transit"
  | "missing";

export type DSCStatus = "active" | "expired" | "revoked";

export interface Database {
  public: {
    Tables: {
      firms: {
        Row: {
          id: string;
          clerk_org_id: string;
          brand_name: string;
          legal_name: string;
          business_entity: string;
          pan_number: string | null;
          gstin: string | null;
          cin_number: string | null;
          tan_number: string | null;
          udyam_number: string | null;
          pt_number: string | null;
          pf_number: string | null;
          esic_number: string | null;
          lut_number: string | null;
          email: string | null;
          phone: string | null;
          website: string | null;
          address_line_1: string | null;
          city: string | null;
          state: string | null;
          pin_code: string | null;
          country: string | null;
          onboarding_step: number;
          onboarding_completed: boolean;
          total_license_seats: number;
          logo_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clerk_org_id: string;
          brand_name: string;
          legal_name: string;
          business_entity?: string;
          pan_number?: string | null;
          gstin?: string | null;
          cin_number?: string | null;
          tan_number?: string | null;
          udyam_number?: string | null;
          pt_number?: string | null;
          pf_number?: string | null;
          esic_number?: string | null;
          lut_number?: string | null;
          email?: string | null;
          phone?: string | null;
          website?: string | null;
          address_line_1?: string | null;
          city?: string | null;
          state?: string | null;
          pin_code?: string | null;
          country?: string | null;
          onboarding_step?: number;
          onboarding_completed?: boolean;
          total_license_seats?: number;
          logo_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clerk_org_id?: string;
          brand_name?: string;
          legal_name?: string;
          business_entity?: string;
          pan_number?: string | null;
          gstin?: string | null;
          cin_number?: string | null;
          tan_number?: string | null;
          udyam_number?: string | null;
          pt_number?: string | null;
          pf_number?: string | null;
          esic_number?: string | null;
          lut_number?: string | null;
          email?: string | null;
          phone?: string | null;
          website?: string | null;
          address_line_1?: string | null;
          city?: string | null;
          state?: string | null;
          pin_code?: string | null;
          country?: string | null;
          onboarding_step?: number;
          onboarding_completed?: boolean;
          total_license_seats?: number;
          logo_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      firm_users: {
        Row: {
          id: string;
          firm_id: string;
          clerk_user_id: string;
          employee_id: string | null;
          first_name: string;
          last_name: string | null;
          full_name: string;
          email: string;
          phone: string | null;
          role: UserRole;
          designation: string | null;
          department: string;
          reporting_to_id: string | null;
          shift: string;
          joining_date: string | null;
          resignation_date: string | null;
          confirmation_date: string | null;
          salary: number;
          cost_per_hour: number;
          billing_rate: number;
          work_experience: string | null;
          employment_status: EmploymentStatus;
          dob: string | null;
          gender: string | null;
          pan_number: string | null;
          aadhaar_number: string | null;
          icai_member_number: string | null;
          icai_student_number: string | null;
          avatar_url: string | null;
          address_line_1: string | null;
          city: string | null;
          state: string | null;
          pin_code: string | null;
          permissions_json: Json;
          is_active: boolean;
          last_punch_in: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          clerk_user_id: string;
          employee_id?: string | null;
          first_name: string;
          last_name?: string | null;
          full_name: string;
          email: string;
          phone?: string | null;
          role?: UserRole;
          designation?: string | null;
          department?: string;
          reporting_to_id?: string | null;
          shift?: string;
          joining_date?: string | null;
          resignation_date?: string | null;
          confirmation_date?: string | null;
          salary?: number;
          cost_per_hour?: number;
          billing_rate?: number;
          work_experience?: string | null;
          employment_status?: EmploymentStatus;
          dob?: string | null;
          gender?: string | null;
          pan_number?: string | null;
          aadhaar_number?: string | null;
          icai_member_number?: string | null;
          icai_student_number?: string | null;
          avatar_url?: string | null;
          address_line_1?: string | null;
          city?: string | null;
          state?: string | null;
          pin_code?: string | null;
          permissions_json?: Json;
          is_active?: boolean;
          last_punch_in?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          clerk_user_id?: string;
          employee_id?: string | null;
          first_name?: string;
          last_name?: string | null;
          full_name?: string;
          email?: string;
          phone?: string | null;
          role?: UserRole;
          designation?: string | null;
          department?: string;
          reporting_to_id?: string | null;
          shift?: string;
          joining_date?: string | null;
          resignation_date?: string | null;
          confirmation_date?: string | null;
          salary?: number;
          cost_per_hour?: number;
          billing_rate?: number;
          work_experience?: string | null;
          employment_status?: EmploymentStatus;
          dob?: string | null;
          gender?: string | null;
          pan_number?: string | null;
          aadhaar_number?: string | null;
          icai_member_number?: string | null;
          icai_student_number?: string | null;
          avatar_url?: string | null;
          address_line_1?: string | null;
          city?: string | null;
          state?: string | null;
          pin_code?: string | null;
          permissions_json?: Json;
          is_active?: boolean;
          last_punch_in?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          firm_id: string;
          lead_code: string;
          lead_name: string;
          contact_person: string;
          business_entity: string;
          deal_value: number;
          currency: string;
          stage: string;
          status: string;
          score: number;
          assigned_to: string | null;
          source: string;
          service_interest: string | null;
          phone: string | null;
          email: string | null;
          gstin: string | null;
          pan: string | null;
          city: string | null;
          state: string | null;
          notes: string | null;
          converted_client_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          lead_code: string;
          lead_name: string;
          contact_person: string;
          business_entity: string;
          deal_value?: number;
          currency?: string;
          stage?: string;
          status?: string;
          score?: number;
          assigned_to?: string | null;
          source?: string;
          service_interest?: string | null;
          phone?: string | null;
          email?: string | null;
          gstin?: string | null;
          pan?: string | null;
          city?: string | null;
          state?: string | null;
          notes?: string | null;
          converted_client_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          lead_code?: string;
          lead_name?: string;
          contact_person?: string;
          business_entity?: string;
          deal_value?: number;
          currency?: string;
          stage?: string;
          status?: string;
          score?: number;
          assigned_to?: string | null;
          source?: string;
          service_interest?: string | null;
          phone?: string | null;
          email?: string | null;
          gstin?: string | null;
          pan?: string | null;
          city?: string | null;
          state?: string | null;
          notes?: string | null;
          converted_client_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      clients: {
        Row: {
          id: string;
          firm_id: string;
          client_code: string;
          trade_name: string;
          legal_name: string;
          entity_type: string;
          pan_number: string | null;
          cin_number: string | null;
          registration_no: string | null;
          primary_gstin: string | null;
          primary_email: string | null;
          primary_phone: string | null;
          contact_name: string | null;
          currency: string | null;
          place_of_supply: string | null;
          address_line_1: string | null;
          address_line_2: string | null;
          city: string | null;
          state: string | null;
          country: string | null;
          pin_code: string | null;
          referred_by: string | null;
          source: string | null;
          client_group: string | null;
          auditor: string | null;
          labels: string[] | null;
          services: string[] | null;
          associate_partners: string | null;
          assigned_partner_id: string | null;
          assigned_manager_id: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          client_code: string;
          trade_name: string;
          legal_name: string;
          entity_type: string;
          pan_number?: string | null;
          cin_number?: string | null;
          registration_no?: string | null;
          primary_gstin?: string | null;
          primary_email?: string | null;
          primary_phone?: string | null;
          contact_name?: string | null;
          currency?: string | null;
          place_of_supply?: string | null;
          address_line_1?: string | null;
          address_line_2?: string | null;
          city?: string | null;
          state?: string | null;
          country?: string | null;
          pin_code?: string | null;
          referred_by?: string | null;
          source?: string | null;
          client_group?: string | null;
          auditor?: string | null;
          labels?: string[] | null;
          services?: string[] | null;
          associate_partners?: string | null;
          assigned_partner_id?: string | null;
          assigned_manager_id?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          client_code?: string;
          trade_name?: string;
          legal_name?: string;
          entity_type?: string;
          pan_number?: string | null;
          cin_number?: string | null;
          registration_no?: string | null;
          primary_gstin?: string | null;
          primary_email?: string | null;
          primary_phone?: string | null;
          contact_name?: string | null;
          currency?: string | null;
          place_of_supply?: string | null;
          address_line_1?: string | null;
          address_line_2?: string | null;
          city?: string | null;
          state?: string | null;
          country?: string | null;
          pin_code?: string | null;
          referred_by?: string | null;
          source?: string | null;
          client_group?: string | null;
          auditor?: string | null;
          labels?: string[] | null;
          services?: string[] | null;
          associate_partners?: string | null;
          assigned_partner_id?: string | null;
          assigned_manager_id?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      services_master: {
        Row: {
          id: string;
          firm_id: string;
          service_code: string;
          service_name: string;
          category: string;
          sac_code: string;
          billing_type: string;
          base_fee: number;
          gst_rate: number;
          estimated_hours: number;
          tat_days: number;
          tat_hours: string | null;
          is_recurring: boolean;
          recurrence_frequency: string | null;
          difficulty_level: string | null;
          description: string | null;
          due_timing: string | null;
          start_day: string | null;
          target_due_day: string | null;
          end_day: string | null;
          exemption_reason: string | null;
          out_of_pocket_budget: number | null;
          sop_count: number | null;
          subtasks_count: number | null;
          notes: string | null;
          is_default: boolean | null;
          subtask_templates: Record<string, unknown>[] | null;
          checklist_templates: Record<string, unknown>[] | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          service_code: string;
          service_name: string;
          category: string;
          sac_code?: string;
          billing_type?: string;
          base_fee?: number;
          gst_rate?: number;
          estimated_hours?: number;
          tat_days?: number;
          tat_hours?: string | null;
          is_recurring?: boolean;
          recurrence_frequency?: string | null;
          difficulty_level?: string | null;
          description?: string | null;
          due_timing?: string | null;
          start_day?: string | null;
          target_due_day?: string | null;
          end_day?: string | null;
          exemption_reason?: string | null;
          out_of_pocket_budget?: number | null;
          sop_count?: number | null;
          subtasks_count?: number | null;
          notes?: string | null;
          is_default?: boolean | null;
          subtask_templates?: Record<string, unknown>[] | null;
          checklist_templates?: Record<string, unknown>[] | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          service_code?: string;
          service_name?: string;
          category?: string;
          sac_code?: string;
          billing_type?: string;
          base_fee?: number;
          gst_rate?: number;
          estimated_hours?: number;
          tat_days?: number;
          tat_hours?: string | null;
          is_recurring?: boolean;
          recurrence_frequency?: string | null;
          difficulty_level?: string | null;
          description?: string | null;
          due_timing?: string | null;
          start_day?: string | null;
          target_due_day?: string | null;
          end_day?: string | null;
          exemption_reason?: string | null;
          out_of_pocket_budget?: number | null;
          sop_count?: number | null;
          subtasks_count?: number | null;
          notes?: string | null;
          is_default?: boolean | null;
          subtask_templates?: Record<string, unknown>[] | null;
          checklist_templates?: Record<string, unknown>[] | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      compliance_tasks: {
        Row: {
          id: string;
          firm_id: string;
          client_id: string;
          service_id: string | null;
          task_code: string | null;
          task_title: string;
          financial_year: string;
          period: string | null;
          start_date: string | null;
          target_date: string;
          due_date: string;
          assigned_to_id: string | null;
          reviewer_id: string | null;
          priority: string;
          stage: string;
          status: string;
          is_billable: boolean;
          proforma_invoice_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          client_id: string;
          service_id?: string | null;
          task_code?: string | null;
          task_title: string;
          financial_year: string;
          period?: string | null;
          start_date?: string | null;
          target_date: string;
          due_date: string;
          assigned_to_id?: string | null;
          reviewer_id?: string | null;
          priority?: string;
          stage?: string;
          status?: string;
          is_billable?: boolean;
          proforma_invoice_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          client_id?: string;
          service_id?: string | null;
          task_code?: string | null;
          task_title?: string;
          financial_year?: string;
          period?: string | null;
          start_date?: string | null;
          target_date?: string;
          due_date?: string;
          assigned_to_id?: string | null;
          reviewer_id?: string | null;
          priority?: string;
          stage?: string;
          status?: string;
          is_billable?: boolean;
          proforma_invoice_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      task_subtasks: {
        Row: {
          id: string;
          task_id: string;
          title: string;
          is_completed: boolean;
          assigned_to_id: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          task_id: string;
          title: string;
          is_completed?: boolean;
          assigned_to_id?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          task_id?: string;
          title?: string;
          is_completed?: boolean;
          assigned_to_id?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      task_activities: {
        Row: {
          id: string;
          firm_id: string;
          task_id: string;
          user_id: string | null;
          action_type: string;
          description: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          task_id: string;
          user_id?: string | null;
          action_type: string;
          description: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          task_id?: string;
          user_id?: string | null;
          action_type?: string;
          description?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      invoices: {
        Row: {
          id: string;
          firm_id: string;
          client_id: string;
          invoice_type: InvoiceType;
          invoice_number: string;
          invoice_date: string;
          due_date: string;
          place_of_supply: string | null;
          subtotal: number;
          cgst_amount: number;
          sgst_amount: number;
          igst_amount: number;
          total_tax: number;
          total_amount: number;
          paid_amount: number;
          tds_amount: number;
          balance_due: number;
          status: string;
          notes: string | null;
          converted_tax_invoice_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          client_id: string;
          invoice_type?: InvoiceType;
          invoice_number: string;
          invoice_date: string;
          due_date: string;
          place_of_supply?: string | null;
          subtotal?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          igst_amount?: number;
          total_tax?: number;
          total_amount?: number;
          paid_amount?: number;
          tds_amount?: number;
          balance_due?: number;
          status?: string;
          notes?: string | null;
          converted_tax_invoice_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          client_id?: string;
          invoice_type?: InvoiceType;
          invoice_number?: string;
          invoice_date?: string;
          due_date?: string;
          place_of_supply?: string | null;
          subtotal?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          igst_amount?: number;
          total_tax?: number;
          total_amount?: number;
          paid_amount?: number;
          tds_amount?: number;
          balance_due?: number;
          status?: string;
          notes?: string | null;
          converted_tax_invoice_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      payment_receipts: {
        Row: {
          id: string;
          firm_id: string;
          client_id: string;
          invoice_id: string | null;
          receipt_number: string;
          receipt_date: string;
          amount_received: number;
          tds_deducted: number;
          payment_mode: string;
          utr_reference: string | null;
          bank_name: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          client_id: string;
          invoice_id?: string | null;
          receipt_number: string;
          receipt_date: string;
          amount_received: number;
          tds_deducted?: number;
          payment_mode?: string;
          utr_reference?: string | null;
          bank_name?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          client_id?: string;
          invoice_id?: string | null;
          receipt_number?: string;
          receipt_date?: string;
          amount_received?: number;
          tds_deducted?: number;
          payment_mode?: string;
          utr_reference?: string | null;
          bank_name?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      attendance_logs: {
        Row: {
          id: string;
          firm_id: string;
          user_id: string;
          attendance_date: string;
          clock_in: string;
          clock_out: string | null;
          total_minutes: number;
          work_location: string;
          client_id: string | null;
          in_geo_coords: string | null;
          out_geo_coords: string | null;
          distance_meters: number | null;
          status: string;
          is_regularized: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          user_id: string;
          attendance_date: string;
          clock_in: string;
          clock_out?: string | null;
          total_minutes?: number;
          work_location?: string;
          client_id?: string | null;
          in_geo_coords?: string | null;
          out_geo_coords?: string | null;
          distance_meters?: number | null;
          status?: string;
          is_regularized?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          user_id?: string;
          attendance_date?: string;
          clock_in?: string;
          clock_out?: string | null;
          total_minutes?: number;
          work_location?: string;
          client_id?: string | null;
          in_geo_coords?: string | null;
          out_geo_coords?: string | null;
          distance_meters?: number | null;
          status?: string;
          is_regularized?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      timesheet_entries: {
        Row: {
          id: string;
          firm_id: string;
          user_id: string;
          client_id: string | null;
          task_id: string | null;
          service_id: string | null;
          entry_date: string;
          hours_spent: number;
          hourly_rate: number;
          cost_rate: number;
          is_billable: boolean;
          work_description: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          user_id: string;
          client_id?: string | null;
          task_id?: string | null;
          service_id?: string | null;
          entry_date: string;
          hours_spent: number;
          hourly_rate?: number;
          cost_rate?: number;
          is_billable?: boolean;
          work_description: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          user_id?: string;
          client_id?: string | null;
          task_id?: string | null;
          service_id?: string | null;
          entry_date?: string;
          hours_spent?: number;
          hourly_rate?: number;
          cost_rate?: number;
          is_billable?: boolean;
          work_description?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      quick_notes: {
        Row: {
          id: string;
          firm_id: string;
          user_id: string;
          title: string;
          content: string;
          tags: string[];
          is_pinned: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          user_id: string;
          title: string;
          content: string;
          tags?: string[];
          is_pinned?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          user_id?: string;
          title?: string;
          content?: string;
          tags?: string[];
          is_pinned?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      dsc_register: {
        Row: {
          id: string;
          firm_id: string;
          client_id: string | null;
          dsc_code: string;
          business_name: string;
          legal_name: string;
          signatory_name: string;
          pan_number: string | null;
          din_number: string | null;
          vendor: string;
          dsc_class: string;
          issued_date: string;
          expiry_date: string;
          location: DSCLocation;
          bin_number: string | null;
          status: DSCStatus;
          email: string | null;
          phone: string | null;
          token_pin_encrypted: string | null;
          token_hardware_model: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          client_id?: string | null;
          dsc_code: string;
          business_name: string;
          legal_name: string;
          signatory_name: string;
          pan_number?: string | null;
          din_number?: string | null;
          vendor?: string;
          dsc_class?: string;
          issued_date: string;
          expiry_date: string;
          location?: DSCLocation;
          bin_number?: string | null;
          status?: DSCStatus;
          email?: string | null;
          phone?: string | null;
          token_pin_encrypted?: string | null;
          token_hardware_model?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          client_id?: string | null;
          dsc_code?: string;
          business_name?: string;
          legal_name?: string;
          signatory_name?: string;
          pan_number?: string | null;
          din_number?: string | null;
          vendor?: string;
          dsc_class?: string;
          issued_date?: string;
          expiry_date?: string;
          location?: DSCLocation;
          bin_number?: string | null;
          status?: DSCStatus;
          email?: string | null;
          phone?: string | null;
          token_pin_encrypted?: string | null;
          token_hardware_model?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_documents: {
        Row: {
          id: string;
          firm_id: string;
          user_id: string;
          document_name: string;
          file_url: string;
          file_size_bytes: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          user_id: string;
          document_name: string;
          file_url: string;
          file_size_bytes?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          user_id?: string;
          document_name?: string;
          file_url?: string;
          file_size_bytes?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      leave_applications: {
        Row: {
          id: string;
          firm_id: string;
          user_id: string;
          leave_type: string;
          from_date: string;
          to_date: string;
          days_count: number;
          reason: string;
          status: string;
          reviewer_id: string | null;
          rejection_remarks: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          user_id: string;
          leave_type: string;
          from_date: string;
          to_date: string;
          days_count: number;
          reason: string;
          status?: string;
          reviewer_id?: string | null;
          rejection_remarks?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          user_id?: string;
          leave_type?: string;
          from_date?: string;
          to_date?: string;
          days_count?: number;
          reason?: string;
          status?: string;
          reviewer_id?: string | null;
          rejection_remarks?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      leave_balances: {
        Row: {
          id: string;
          firm_id: string;
          user_id: string;
          financial_year: string;
          casual_leave_quota: number;
          casual_leave_taken: number;
          sick_leave_quota: number;
          sick_leave_taken: number;
          exam_leave_quota: number;
          exam_leave_taken: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          user_id: string;
          financial_year: string;
          casual_leave_quota?: number;
          casual_leave_taken?: number;
          sick_leave_quota?: number;
          sick_leave_taken?: number;
          exam_leave_quota?: number;
          exam_leave_taken?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          user_id?: string;
          financial_year?: string;
          casual_leave_quota?: number;
          casual_leave_taken?: number;
          sick_leave_quota?: number;
          sick_leave_taken?: number;
          exam_leave_quota?: number;
          exam_leave_taken?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      employee_expense_claims: {
        Row: {
          id: string;
          firm_id: string;
          user_id: string;
          claim_date: string;
          reason: string;
          amount: number;
          receipt_url: string | null;
          status: string;
          is_settled: boolean;
          settled_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          user_id: string;
          claim_date: string;
          reason: string;
          amount: number;
          receipt_url?: string | null;
          status?: string;
          is_settled?: boolean;
          settled_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          user_id?: string;
          claim_date?: string;
          reason?: string;
          amount?: number;
          receipt_url?: string | null;
          status?: string;
          is_settled?: boolean;
          settled_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      client_gstins: {
        Row: {
          id: string;
          firm_id: string;
          client_id: string;
          gstin: string;
          state: string;
          state_code: string;
          principal_place: string | null;
          is_primary: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          client_id: string;
          gstin: string;
          state: string;
          state_code: string;
          principal_place?: string | null;
          is_primary?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          client_id?: string;
          gstin?: string;
          state?: string;
          state_code?: string;
          principal_place?: string | null;
          is_primary?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      client_contacts: {
        Row: {
          id: string;
          firm_id: string;
          client_id: string;
          name: string;
          designation: string | null;
          email: string | null;
          phone: string | null;
          din_number: string | null;
          is_primary: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          client_id: string;
          name: string;
          designation?: string | null;
          email?: string | null;
          phone?: string | null;
          din_number?: string | null;
          is_primary?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          client_id?: string;
          name?: string;
          designation?: string | null;
          email?: string | null;
          phone?: string | null;
          din_number?: string | null;
          is_primary?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      client_licenses: {
        Row: {
          id: string;
          firm_id: string;
          client_id: string;
          license_name: string;
          license_number: string;
          issuing_authority: string | null;
          issue_date: string | null;
          expiry_date: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          client_id: string;
          license_name: string;
          license_number: string;
          issuing_authority?: string | null;
          issue_date?: string | null;
          expiry_date?: string | null;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          client_id?: string;
          license_name?: string;
          license_number?: string;
          issuing_authority?: string | null;
          issue_date?: string | null;
          expiry_date?: string | null;
          status?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      invoice_items: {
        Row: {
          id: string;
          invoice_id: string;
          service_id: string | null;
          description: string;
          sac_code: string;
          quantity: number;
          rate: number;
          taxable_value: number;
          gst_rate: number;
          cgst_amount: number;
          sgst_amount: number;
          igst_amount: number;
          total_amount: number;
          is_reimbursement: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          service_id?: string | null;
          description: string;
          sac_code?: string;
          quantity?: number;
          rate?: number;
          taxable_value?: number;
          gst_rate?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          igst_amount?: number;
          total_amount?: number;
          is_reimbursement?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          service_id?: string | null;
          description?: string;
          sac_code?: string;
          quantity?: number;
          rate?: number;
          taxable_value?: number;
          gst_rate?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          igst_amount?: number;
          total_amount?: number;
          is_reimbursement?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      client_reimbursements: {
        Row: {
          id: string;
          firm_id: string;
          client_id: string;
          expense_date: string;
          category: string;
          description: string;
          amount: number;
          challan_number: string | null;
          receipt_url: string | null;
          is_billed: boolean;
          invoice_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          client_id: string;
          expense_date: string;
          category: string;
          description: string;
          amount: number;
          challan_number?: string | null;
          receipt_url?: string | null;
          is_billed?: boolean;
          invoice_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          client_id?: string;
          expense_date?: string;
          category?: string;
          description?: string;
          amount?: number;
          challan_number?: string | null;
          receipt_url?: string | null;
          is_billed?: boolean;
          invoice_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      recurring_invoices: {
        Row: {
          id: string;
          firm_id: string;
          client_id: string;
          frequency: string;
          amount: number;
          start_date: string;
          end_date: string | null;
          next_run_date: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          client_id: string;
          frequency: string;
          amount: number;
          start_date: string;
          end_date?: string | null;
          next_run_date: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          client_id?: string;
          frequency?: string;
          amount?: number;
          start_date?: string;
          end_date?: string | null;
          next_run_date?: string;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      dsc_movement_logs: {
        Row: {
          id: string;
          firm_id: string;
          dsc_id: string;
          from_location: string | null;
          to_location: string;
          from_bin: string | null;
          to_bin: string | null;
          handed_to: string | null;
          reason: string | null;
          logged_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          firm_id: string;
          dsc_id: string;
          from_location?: string | null;
          to_location: string;
          from_bin?: string | null;
          to_bin?: string | null;
          handed_to?: string | null;
          reason?: string | null;
          logged_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          firm_id?: string;
          dsc_id?: string;
          from_location?: string | null;
          to_location?: string;
          from_bin?: string | null;
          to_bin?: string | null;
          handed_to?: string | null;
          reason?: string | null;
          logged_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      user_role: UserRole;
      employment_status_enum: EmploymentStatus;
      invoice_type_enum: InvoiceType;
      dsc_location_enum: DSCLocation;
      dsc_status_enum: DSCStatus;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
